import type { ThemeDefinition } from 'vuetify'

const light: ThemeDefinition = {
  dark: false,
  colors: {
    background: '#f5ece7',
    surface: '#fff8f5',
    'surface-dim': '#e1d8d4',
    'surface-bright': '#fff8f5',
    'surface-container-lowest': '#ffffff',
    'surface-container-low': '#fbf2ed',
    'surface-container': '#f5ece7',
    'surface-container-high': '#efe7e1',
    'surface-container-highest': '#e9e1dc',
    'on-surface': '#1e1b18',
    'inverse-surface': '#34302c',
    'inverse-on-surface': '#f8efea',
    outline: '#80756a',
    'outline-variant': '#d2c4b7',
    primary: '#775935',
    'on-primary': '#ffffff',
    'primary-container': '#ffddb8',
    'on-primary-container': '#2a1700',
    'inverse-primary': '#e7c094',
    secondary: '#556161',
    'on-secondary': '#ffffff',
    'secondary-container': '#d9e5e5',
    'on-secondary-container': '#121d1e',
    tertiary: '#685e34',
    'on-tertiary': '#ffffff',
    'tertiary-container': '#f0e3ad',
    'on-tertiary-container': '#211b00',
    error: '#ba1a1a',
    'on-error': '#ffffff',
    'error-container': '#ffdad6',
    'on-error-container': '#410002',
    success: '#2e7d32',
    'on-success': '#ffffff',
    'success-container': '#c8e6c9',
    'on-success-container': '#1b5e20',
    warning: '#f57c00',
    'on-warning': '#ffffff',
    'warning-container': '#ffe0b2',
    'on-warning-container': '#e65100',
    info: '#0288d1',
    'on-info': '#ffffff',
    'info-container': '#b3e5fc',
    'on-info-container': '#01579b',
    'primary-fixed': '#ffddb8',
    'primary-fixed-dim': '#e7c094',
    'on-primary-fixed': '#2a1700',
    'on-primary-fixed-variant': '#5c4120',
    'secondary-fixed': '#d9e5e5',
    'secondary-fixed-dim': '#bdc9c9',
    'on-secondary-fixed': '#121d1e',
    'on-secondary-fixed-variant': '#3d4949',
    'tertiary-fixed': '#f0e3ad',
    'tertiary-fixed-dim': '#d3c793',
    'on-tertiary-fixed': '#211b00',
    'on-tertiary-fixed-variant': '#4f471f',
    'surface-light': '#efe7e1',
  },
  variables: {
    'overlay-background': '#211a12',
  },
}

const dark: ThemeDefinition = {
  dark: true,
  colors: {
    background: '#231f1c',
    surface: '#161310',
    'surface-dim': '#161310',
    'surface-bright': '#3d3835',
    'surface-container-lowest': '#110e0b',
    'surface-container-low': '#1e1b18',
    'surface-container': '#231f1c',
    'surface-container-high': '#2d2926',
    'surface-container-highest': '#383431',
    'on-surface': '#e9e1dc',
    'inverse-surface': '#e9e1dc',
    'inverse-on-surface': '#34302c',
    outline: '#9b8f83',
    'outline-variant': '#4e453c',
    primary: '#e7c094',
    'on-primary': '#432b0b',
    'primary-container': '#5c4120',
    'on-primary-container': '#ffddb8',
    'inverse-primary': '#775935',
    secondary: '#bdc9c9',
    'on-secondary': '#273233',
    'secondary-container': '#3d4949',
    'on-secondary-container': '#d9e5e5',
    tertiary: '#d3c793',
    'on-tertiary': '#38300a',
    'tertiary-container': '#4f471f',
    'on-tertiary-container': '#f0e3ad',
    error: '#ffb4ab',
    'on-error': '#690005',
    'error-container': '#93000a',
    'on-error-container': '#ffb4ab',
    success: '#81c784',
    'on-success': '#1b5e20',
    'success-container': '#2e7d32',
    'on-success-container': '#c8e6c9',
    warning: '#ffb74d',
    'on-warning': '#e65100',
    'warning-container': '#f57c00',
    'on-warning-container': '#ffe0b2',
    info: '#4fc3f7',
    'on-info': '#01579b',
    'info-container': '#0288d1',
    'on-info-container': '#b3e5fc',
    'primary-fixed': '#ffddb8',
    'primary-fixed-dim': '#e7c094',
    'on-primary-fixed': '#2a1700',
    'on-primary-fixed-variant': '#5c4120',
    'secondary-fixed': '#d9e5e5',
    'secondary-fixed-dim': '#bdc9c9',
    'on-secondary-fixed': '#121d1e',
    'on-secondary-fixed-variant': '#3d4949',
    'tertiary-fixed': '#f0e3ad',
    'tertiary-fixed-dim': '#d3c793',
    'on-tertiary-fixed': '#211b00',
    'on-tertiary-fixed-variant': '#4f471f',
    'surface-light': '#3d3835',
  },
  variables: {
    'overlay-background': '#211a12',
  },
}

export default {
  defaultTheme: 'light',
  themes: {
    light,
    dark,
  },
}
