import type { ThemeDefinition } from "vuetify";

const light: ThemeDefinition = {
  dark: false,
  colors: {
    background: "#f3ecea",
    surface: "#fff8f6",
    "surface-dim": "#dfd9d7",
    "surface-bright": "#fff8f6",
    "surface-container-lowest": "#ffffff",
    "surface-container-low": "#f9f2f0",
    "surface-container": "#f3ecea",
    "surface-container-high": "#ede7e5",
    "surface-container-highest": "#e8e1df",
    "on-surface": "#1d1b1a",
    "inverse-surface": "#33302f",
    "inverse-on-surface": "#f6efed",
    outline: "#877369",
    "outline-variant": "#dac2b6",
    primary: "#914b20",
    "on-primary": "#ffffff",
    "primary-container": "#ffdbca",
    "on-primary-container": "#331200",
    "inverse-primary": "#ffb68e",
    secondary: "#695c4e",
    "on-secondary": "#ffffff",
    "secondary-container": "#f1e0ce",
    "on-secondary-container": "#231a0f",
    tertiary: "#416372",
    "on-tertiary": "#ffffff",
    "tertiary-container": "#c4e8fa",
    "on-tertiary-container": "#001f2a",
    error: "#ba1a1a",
    "on-error": "#ffffff",
    "error-container": "#ffdad6",
    "on-error-container": "#410002",
    "primary-fixed": "#ffdbca",
    "primary-fixed-dim": "#ffb68e",
    "on-primary-fixed": "#331200",
    "on-primary-fixed-variant": "#743509",
    "secondary-fixed": "#f1e0ce",
    "secondary-fixed-dim": "#d4c4b3",
    "on-secondary-fixed": "#231a0f",
    "on-secondary-fixed-variant": "#504538",
    "tertiary-fixed": "#c4e8fa",
    "tertiary-fixed-dim": "#a9ccdd",
    "on-tertiary-fixed": "#001f2a",
    "on-tertiary-fixed-variant": "#294b5a",
    "surface-light": "#ede7e5",
  },
  variables: {
    "overlay-background": "#261911",
  },
};

const dark: ThemeDefinition = {
  dark: true,
  colors: {
    background: "#221f1e",
    surface: "#151312",
    "surface-dim": "#151312",
    "surface-bright": "#3c3837",
    "surface-container-lowest": "#100e0d",
    "surface-container-low": "#1d1b1a",
    "surface-container": "#221f1e",
    "surface-container-high": "#2c2928",
    "surface-container-highest": "#373433",
    "on-surface": "#e8e1df",
    "inverse-surface": "#e8e1df",
    "inverse-on-surface": "#33302f",
    outline: "#a28c82",
    "outline-variant": "#54433a",
    primary: "#ffb68e",
    "on-primary": "#542200",
    "primary-container": "#743509",
    "on-primary-container": "#ffdbca",
    "inverse-primary": "#914b20",
    secondary: "#d4c4b3",
    "on-secondary": "#392f23",
    "secondary-container": "#504538",
    "on-secondary-container": "#f1e0ce",
    tertiary: "#a9ccdd",
    "on-tertiary": "#0f3442",
    "tertiary-container": "#294b5a",
    "on-tertiary-container": "#c4e8fa",
    error: "#ffb4ab",
    "on-error": "#690005",
    "error-container": "#93000a",
    "on-error-container": "#ffb4ab",
    "primary-fixed": "#ffdbca",
    "primary-fixed-dim": "#ffb68e",
    "on-primary-fixed": "#331200",
    "on-primary-fixed-variant": "#743509",
    "secondary-fixed": "#f1e0ce",
    "secondary-fixed-dim": "#d4c4b3",
    "on-secondary-fixed": "#231a0f",
    "on-secondary-fixed-variant": "#504538",
    "tertiary-fixed": "#c4e8fa",
    "tertiary-fixed-dim": "#a9ccdd",
    "on-tertiary-fixed": "#001f2a",
    "on-tertiary-fixed-variant": "#294b5a",
    "surface-light": "#3c3837",
  },
  variables: {
    "overlay-background": "#261911",
  },
};

export default {
  defaultTheme: "light",
  themes: {
    light,
    dark,
  },
};
